services:

  mariadb:
    image: mariadb:11
    container_name: gym_mariadb

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: gym_db

    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql     # named volume, fresh initialization
      - ./db:/docker-entrypoint-initdb.d


  backend:
    build:
      context: ./backend

    environment:
      DATABASE_HOST: mariadb
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: gym_db

    ports:
      - "5000:5000"

    depends_on:
      - mariadb

  # =========================
  # FRONTEND
  # =========================
  frontend:
    build:
      context: ./frontend

    container_name: gym_frontend

    restart: always

    ports:
      - "5173:5173"

    depends_on:
      - backend

    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mariadb_data:
