allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@hono/node-server@1.19.13'
  - '@hono/node-server@2.0.5'
  - fast-uri@3.1.4
  - valibot@1.4.2
  - fast-uri@3.1.5
  - hono@4.12.34
