-- =========================================================
-- ENUM TYPES
-- =========================================================

CREATE TYPE duration_type AS ENUM (
    'Week',
    'Month',
    'Day'
);

CREATE TYPE user_role AS ENUM (
    'ADMIN',
    'MEMBER'
);

CREATE TYPE tutorial_level AS ENUM (
    'Beginner',
    'Intermediate',
    'Advanced'
);

CREATE TYPE member_gender AS ENUM (
    'Male',
    'Female'
);

CREATE TYPE otp_purpose AS ENUM (
    'LOGIN',
    'RESET_PASSWORD',
    'VERIFY_EMAIL'
);

CREATE TYPE reward_redemption_status AS ENUM (
    'Pending',
    'Claimed',
    'Cancelled'
);

CREATE TYPE membership_status AS ENUM (
    'Active',
    'Expired',
    'Cancelled'
);

CREATE TYPE payment_method AS ENUM (
    'Cash',
    'GCash',
    'Bank Transfer'
);

CREATE TYPE payment_type AS ENUM (
    'Membership',
    'Renewal',
    'Upgrade',
    'Refund'
);

CREATE TYPE payment_status AS ENUM (
    'Paid',
    'Refunded'
);

CREATE TYPE attendance_status AS ENUM (
    'PRESENT'
);

CREATE TYPE recipient_type AS ENUM (
    'ADMIN',
    'MEMBER'
);

CREATE TYPE activity_category AS ENUM (
    'PAYMENT',
    'MEMBERSHIP',
    'REWARD',
    'MEMBER',
    'ATTENDANCE',
    'PRICING',
    'WORKOUT'
);

CREATE TYPE notification_category AS ENUM (
    'PAYMENT',
    'MEMBERSHIP',
    'REWARD',
    'MEMBER',
    'ATTENDANCE'
);

CREATE TYPE notification_type AS ENUM (
    'MEMBERSHIP_EXPIRED',
    'MEMBERSHIP_EXPIRING',
    'MEMBERSHIP_UPGRADE',
    'PAYMENT_RECORDED',
    'MEMBER_ADDED',
    'MEMBER_INACTIVE_3_DAYS',
    'MEMBER_INACTIVE_7_DAYS',
    'MEMBER_INACTIVE_14_DAYS',
    'REWARD_CLAIMED',
    'ATTENDANCE_POINTS',
    'REWARD_CANCELLED'
);

CREATE TYPE fitness_goal_type AS ENUM (
    'LOSE_WEIGHT',
    'GAIN_WEIGHT'
);

CREATE TYPE fitness_goal_status AS ENUM (
    'ACHIEVED',
    'ACTIVE'
);


-- =========================================================
-- MEMBERSHIP PLANS
-- =========================================================

CREATE TABLE membership_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    duration INTEGER NOT NULL,
    duration_type duration_type NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- USERS
-- =========================================================

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    hash_pass TEXT NOT NULL,
    profile VARCHAR(255),
    role user_role NOT NULL DEFAULT 'MEMBER',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- CHECK-IN SESSIONS
-- =========================================================

CREATE TABLE checkin_sessions (
    id VARCHAR(36) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);


-- =========================================================
-- TUTORIALS
-- =========================================================

CREATE TABLE tutorials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    level tutorial_level NOT NULL,
    video_url VARCHAR(500) NOT NULL,
    instructions TEXT NOT NULL,
    equipment JSONB NOT NULL,
    muscles_targeted JSONB NOT NULL,
    demo_images JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- REWARDS
-- =========================================================

CREATE TABLE rewards (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    points_required INTEGER NOT NULL,
    category VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- MEMBERS
-- =========================================================

CREATE TABLE members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER UNIQUE,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    age INTEGER NOT NULL,
    gender member_gender NOT NULL,
    is_activated BOOLEAN NOT NULL DEFAULT FALSE,
    points INTEGER NOT NULL,
    referral_code VARCHAR(255) NOT NULL UNIQUE,
    join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_members_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);


-- =========================================================
-- OTP CODES
-- =========================================================

CREATE TABLE otp_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    code VARCHAR(10) NOT NULL,
    purpose otp_purpose NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_otp
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


-- =========================================================
-- REWARD REDEMPTIONS
-- =========================================================

CREATE TABLE reward_redemptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    reward_id INTEGER NOT NULL,
    points_used INTEGER NOT NULL,
    status reward_redemption_status DEFAULT 'Pending',
    redeemed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reward_member_redeemed
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_reward_redeemed
        FOREIGN KEY (reward_id)
        REFERENCES rewards(id)
);


-- =========================================================
-- MEMBER ACTIVATIONS
-- =========================================================

CREATE TABLE member_activations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    activation_code VARCHAR(10) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    is_used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_member_activations
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE
);


-- =========================================================
-- MEMBER MEMBERSHIPS
-- =========================================================

CREATE TABLE member_memberships (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    plan_id INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status membership_status DEFAULT 'Active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_member_membership_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_member_membership_plan
        FOREIGN KEY (plan_id)
        REFERENCES membership_plans(id)
        ON DELETE RESTRICT
);


-- =========================================================
-- PAYMENTS
-- =========================================================

CREATE TABLE payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    membership_id INTEGER NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    payment_method payment_method NULL,
    payment_type payment_type NOT NULL,
    status payment_status DEFAULT 'Paid',
    description VARCHAR(255) NULL,
    paid_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_payment_membership
        FOREIGN KEY (membership_id)
        REFERENCES member_memberships(id)
        ON DELETE CASCADE
);


-- =========================================================
-- ATTENDANCE
-- =========================================================

CREATE TABLE attendance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    session_id VARCHAR(36) NOT NULL,
    check_in_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status attendance_status DEFAULT 'PRESENT',

    CONSTRAINT fk_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_session
        FOREIGN KEY (session_id)
        REFERENCES checkin_sessions(id)
        ON DELETE CASCADE,

    CONSTRAINT unique_member_session
        UNIQUE (member_id, session_id)
);


-- =========================================================
-- ACTIVITIES
-- =========================================================

CREATE TABLE activities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id INTEGER NULL,
    recipient_type recipient_type NOT NULL,
    category activity_category,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_member_activities
        FOREIGN KEY (recipient_id)
        REFERENCES members(id)
        ON DELETE CASCADE
);


-- =========================================================
-- NOTIFICATIONS
-- =========================================================

CREATE TABLE notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id INTEGER NULL,
    recipient_type recipient_type NOT NULL,
    category notification_category,
    type notification_type NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_member_notifications
        FOREIGN KEY (recipient_id)
        REFERENCES members(id)
        ON DELETE CASCADE
);


-- =========================================================
-- MEMBER WORKOUTS
-- =========================================================

CREATE TABLE member_workouts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    workout_name VARCHAR(150) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_member_workouts
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE
);


-- =========================================================
-- MEMBER WORKOUT EXERCISES
-- =========================================================

CREATE TABLE member_workout_exercises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id INTEGER NOT NULL,
    exercise_name VARCHAR(150) NOT NULL,
    sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    weight DECIMAL(6,2) NOT NULL,

    CONSTRAINT fk_member_workouts_exercises
        FOREIGN KEY (workout_id)
        REFERENCES member_workouts(id)
        ON DELETE CASCADE
);


-- =========================================================
-- POSTS
-- =========================================================

CREATE TABLE posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_posts_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE
);


-- =========================================================
-- POST IMAGES
-- =========================================================

CREATE TABLE post_images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL,
    image_url TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_post_images_post
        FOREIGN KEY (post_id)
        REFERENCES posts(id)
        ON DELETE CASCADE
);


-- =========================================================
-- POST LIKES
-- =========================================================

CREATE TABLE post_likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL,
    member_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_post_likes_post
        FOREIGN KEY (post_id)
        REFERENCES posts(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_post_likes_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_post_likes_member_post
        UNIQUE (post_id, member_id)
);


-- =========================================================
-- POST COMMENTS
-- =========================================================

CREATE TABLE post_comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL,
    member_id INTEGER NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_post_comments_post
        FOREIGN KEY (post_id)
        REFERENCES posts(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_post_comments_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE
);


-- =========================================================
-- FITNESS GOALS
-- =========================================================

CREATE TABLE fitness_goals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL,
    goal_type fitness_goal_type NOT NULL,
    status fitness_goal_status NOT NULL DEFAULT 'ACTIVE',
    start_weight DECIMAL(5,2) NOT NULL,
    current_weight DECIMAL(5,2) NOT NULL,
    target_weight DECIMAL(5,2) NOT NULL,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_goal_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE
);


-- =========================================================
-- BODY PROGRESS
-- =========================================================

CREATE TABLE body_progress (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id INTEGER NOT NULL,
    member_id INTEGER NOT NULL,
    previous_weight DECIMAL(5,2) NOT NULL,
    current_weight DECIMAL(5,2) NOT NULL,
    target_weight DECIMAL(5,2) NOT NULL,
    progress_percentage DECIMAL(5,2) NOT NULL DEFAULT 0,
    weight_change DECIMAL(5,2) NOT NULL DEFAULT 0,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_progress_goal
        FOREIGN KEY (goal_id)
        REFERENCES fitness_goals(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_progress_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE
);


-- =========================================================
-- REFERRALS
-- =========================================================

CREATE TABLE referrals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id INTEGER NOT NULL,
    referee_id INTEGER NOT NULL,
    referrer_points INTEGER NOT NULL,
    referee_points INTEGER NOT NULL,
    referred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_referrer
        FOREIGN KEY (referrer_id)
        REFERENCES members(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_referee
        FOREIGN KEY (referee_id)
        REFERENCES members(id)
        ON DELETE CASCADE,

    CONSTRAINT unique_referee
        UNIQUE (referee_id)
);


-- =========================================================
-- UPDATED_AT TRIGGER FUNCTION
-- =========================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION update_updatedAt_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW."updatedAt" = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- =========================================================
-- UPDATED_AT TRIGGERS
-- =========================================================

CREATE TRIGGER update_membership_plans_updated_at
BEFORE UPDATE ON membership_plans
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


CREATE TRIGGER update_users_updatedAt
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updatedAt_column();


CREATE TRIGGER update_rewards_updatedAt
BEFORE UPDATE ON rewards
FOR EACH ROW
EXECUTE FUNCTION update_updatedAt_column();


CREATE TRIGGER update_member_activations_updated_at
BEFORE UPDATE ON member_activations
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


CREATE TRIGGER update_member_memberships_updated_at
BEFORE UPDATE ON member_memberships
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


CREATE TRIGGER update_posts_updated_at
BEFORE UPDATE ON posts
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


CREATE TRIGGER update_post_comments_updated_at
BEFORE UPDATE ON post_comments
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


CREATE TRIGGER update_fitness_goals_updated_at
BEFORE UPDATE ON fitness_goals
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();